[profile.default]
src = "src"
test = "test"
out = "out"
libs = ["lib"]

# --- Solidity setup ---
solc_version = "0.8.21"
optimizer = true
optimizer_runs = 200
auto_detect_solc = true

# --- Gas + Deployment ---
legacy = true
gas_price = 15000000000  # 15 gwei (integer, not string)
chain_id = 11155111

# --- Etherscan verification ---
etherscan_api_key = "${ETHERSCAN_API_KEY}"

# --- Dependencies ---
remappings = [
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
  "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
  "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/",
  "foundry-devops/=lib/foundry-devops/src/",
    "forge-std/=lib/forge-std/src/",
    "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/src/v0.8/",
  "@chainlink/contracts/=lib/chainlink/contracts/"
]

# --- Known RPCs ---
[profile.chains]
sepolia = { chain_id = 11155111, rpc_url = "${SEPOLIA_RPC_URL}" }
