name: Foundry CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    # Change to windows-latest if you prefer Windows
    runs-on: macos-latest

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Install Foundry
      - name: Install Foundry
        run: |
          curl -L https://foundry.paradigm.xyz | bash
          foundryup

      # 3. Add Foundry binaries to PATH
      - name: Set PATH for Foundry
        run: |
          echo "$HOME/.foundry/bin" >> $GITHUB_PATH

      # 4. Verify installation
      - name: Verify Foundry
        run: |
          forge --version
          cast --version

      # 5. Optional: Install dependencies
      # Uncomment and modify if you have other dependencies
      # - name: Install dependencies
      #   run: |
      #     npm install
      #     pip install -r requirements.txt

      # 6. Build the project
      - name: Build project
        run: forge build

      # 7. Run tests
      - name: Run tests
        # Remove --fork-url if you don't need forked mainnet tests
        run: forge test --fork-url https://eth-mainnet.alchemyapi.io/v2/YOUR_ALCHEMY_KEY
