name: Foundry CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 🧱 Install Foundry properly and make sure PATH persists
      - name: Install Foundry
        run: |
          curl -L https://foundry.paradigm.xyz | bash
          echo "$HOME/.foundry/bin" >> $GITHUB_PATH
          source $HOME/.bashrc || true
          foundryup

      # 🧩 Verify installation
      - name: Verify Foundry
        run: |
          forge --version
          cast --version

      # 🧱 Install dependencies
      - name: Install dependencies
        run: |
          forge install foundry-rs/forge-std --no-commit
          forge install smartcontractkit/chainlink-brownie-contracts --no-commit
          forge install Cyfrin/foundry-devops --no-commit

      # 🧪 Build and Test
      - name: Build and Test
        run: |
          forge build --sizes
          forge test -vvv

