name: Foundry CI Bulletproof

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Foundry
        run: |
          curl -L https://foundry.paradigm.xyz | bash
          export PATH="$PATH:/home/runner/.foundry/bin"
          foundryup

      - name: Build contracts
        working-directory: ./foundry-task-self
        run: forge build

      - name: Run tests
        working-directory: ./foundry-task-self
        run: forge test -vvv
