name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        run: |
          curl -L https://foundry.paradigm.xyz | bash
          foundryup

      - name: Install dependencies
        run: forge install

      - name: Build
        run: forge build

      - name: Test
        run: forge test

