name: Foundry CI Bulletproof

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Foundry
        shell: bash
        run: |
          curl -L https://foundry.paradigm.xyz | bash
          echo "/home/runner/.foundry/bin" >> $GITHUB_PATH
          foundryup

      - name: Verify Foundry installation
        run: forge --version

      - name: Build contracts
        working-directory: ./foundry-task-self
        run: forge build

      - name: Run tests
        working-directory: ./foundry-task-self
        run: forge test -vvv
