name: Foundry CI Robust

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
      # 1. Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Install Foundry
      - name: Install Foundry
        run: |
          curl -L https://foundry.paradigm.xyz | bash
          foundryup
          echo "$HOME/.foundry/bin" >> $GITHUB_PATH

      # 3. Verify Foundry installation
      - name: Verify Foundry
        run: |
          echo "Current PATH: $PATH"
          which forge
          forge --version
          cast --version

      # 4. Build the project
      - name: Build project
        run: forge build

      # 5. Run tests (simplified)
      - name: Run tests
        run: forge test
